
/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of PriceEstimateCollection
 *
 * @constructor
 */
PriceEstimateCollection = function (obj) {
    if(!obj) {
        this.prices = null;     
    } else {
        this.prices = obj.prices.map(function(model){
            return new PriceEsitmate(model);
        });
    }
};

PriceEstimateCollection.prototype = new BaseModel();
PriceEstimateCollection.prototype.constructor = PriceEstimateCollection;

/**
 * List of price estimates
 *
 * @return {array}
 */
PriceEstimateCollection.prototype.getPrices = function() {
    return this.prices;
};

/**
 * Setter for Prices
 * 
 * @param {array} value 
 */
PriceEstimateCollection.prototype.setPrices = function(value) {
    this.prices = value;
};


module.exports = PriceEstimateCollection;