
/**
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of ProductCollection
 *
 * @constructor
 */
ProductCollection = function (obj) {
    if(!obj) {
        this.products = null;     
    } else {
        this.products = obj.products.map(function(model){
            return new Product(model);
        });
    }
};

ProductCollection.prototype = new BaseModel();
ProductCollection.prototype.constructor = ProductCollection;

/**
 * List of products
 *
 * @return {array}
 */
ProductCollection.prototype.getProducts = function() {
    return this.products;
};

/**
 * Setter for Products
 * 
 * @param {array} value 
 */
ProductCollection.prototype.setProducts = function(value) {
    this.products = value;
};


module.exports = ProductCollection;